### ISSUE TITLE
SelectBox-Popup does ignores element count when displaying

### ISSUE THREAD

**Issue by GeMoschen** [SpinyOwl/legui#100]
https://github.com/SpinyOwl/legui/blob/f31b738bf9ab3cb358dc4daa31e89470333de01a/src/main/java/org/liquidengine/legui/component/misc/animation/selectbox/SelectBoxAnimation.java#L49

The popup of the SelectBox ignores the current element count, if the current element count is below the visibleCount of the SelectBox. 

Changing the line to the following code fixes it.

`int visibleCount = Math.min(selectBox.getElements().size(), selectBox.getVisibleCount());`

**Comment by ShchAlexander** [comment]
Hello @GeMoschen, fix is published under `1.4.7-SNAPSHOT` version.
