### ISSUE TITLE
Demo does not work properly

### ISSUE THREAD

**Issue by byxiaobai** [SpinyOwl/legui#105]
It prompts "The import org.liquidengine.legui.system.layout cannot be resolved"

**Comment by ShchAlexander** [comment]
Hello @byxiaobai, could you please post more details here?
With what are you trying to import project?
What exactly class that IDE could not import?
Java version you use to work with project?

**Comment by byxiaobai** [comment]
Now the Demo can run normally.
I tried to use legui in my own game, but I don't know which libraries to add.

**Comment by byxiaobai** [comment]
Well. . I found that the problem was caused by my own settings.Thanks!

**Comment by ShchAlexander** [comment]
If you use maven/gradle it should automatically download all dependencies, so it should work properly without any additional libraries.
If you want to use up-to-date libraries - please check `dependencies` section in build script [build.gradle](https://github.com/SpinyOwl/legui/blob/develop/build.gradle)

Regards,
Alex
