### ISSUE TITLE
SelectBox not working within a Dialog

### ISSUE THREAD

**Issue by hcsfred** [SpinyOwl/legui#110]
If the SelectBox option lies outside the bounds of the Dialog, it cannot be clicked. If within bounds, it can be clicked but the value of the SelectBox does not change. In both cases, no SelectBoxChangeSelectionEvent is triggered.

Example code:
```
val dialog = Dialog(260f, 70f)
val dropdown = SelectBox<String>(20f, 20f, 80f, 15f)
dropdown.addElement("1")
dropdown.addElement("2")
dropdown.addElement("3")
dialog.container.add(dropdown)
dialog.show(frame)
```

**Comment by ShchAlexander** [comment]
Fixed
