### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by Thewbi** [SpinyOwl/legui#172]
I like legui very much!

I am looking for a way to increase the size of UI elements on displays featuring a very high resolution.

I tried glfwWindowHint(GLFW_SCALE_TO_MONITOR, 1);
and in the NvgRenderer I tried to use nvgScale(nvgContext, 2.0f, 2.0f);

Both approaches merely scale the UI but the processing of mouse events is still based on a non-scaled coordinate system. 
Long story short, I haven't found a way to scale the UI.
On high res screens the UI is to small. The users cannot read the font.

Is there a way to scale the UI on screens with a high resolution?

Thanks.

**Comment by SpinyOwl** [comment]
Hello @Thewbi!

Thank you for your words. Could you please add some images that could demonstrate your issue?

Kind regards

**Comment by Thewbi** [comment]
Hi, sure thing.

here is a picture that shows the issue. As a reference you see the browser to the right which has "normal" scaling in my opinion, at least it is very readable on my screen whereas the legui does not scale the same way and remains harder to read.
![SpinyOwl_legui](https://github.com/SpinyOwl/legui/assets/34318169/61706c07-fb48-4ace-b5b8-382a0f8e410d)

And here is a hack that I made to scale the UI:
![SpinyOwl_legui_Hack](https://github.com/SpinyOwl/legui/assets/34318169/9bb870c2-1e43-4b83-b283-87601d6709ed)

Here are the changes I made:

In com.spinyowl.legui.system.handler.CursorPosEventHandler divide mouse positions by 2 because the UI was blown up by factor two and the user will now click two times more off to the side when pointing the mouse cursor to a UI element.

```
protected void preHandle(SystemCursorPosEvent event, Frame frame, Context context) {
    // UI scaling hack
    Vector2f cursorPosition = new Vector2f(event.fx / 2, event.fy / 2);
    ...
```
and in com.spinyowl.legui.system.renderer.nvg.NvgRenderer nvgScale using a factor of 2 which upscales everything to twice the size.
```
@Override
  protected void preRender(Context context) {
    loadFontsToNvg();
    context.getContextData().put(NVG_CONTEXT, nvgContext);

    glDisable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    Vector2i windowSize = context.getWindowSize();
    nvgBeginFrame(nvgContext, windowSize.x, windowSize.y, context.getPixelRatio());

    // UI scaling hack
    nvgScale(nvgContext, 2.0f, 2.0f);
  }
```

**Comment by SpinyOwl** [comment]
Thank you so much for the details!

I'll try to provide an update in a few days. 
Already found a way to get scaling from GLFW.
Change in fact would be not as simple as it could, cause legui does not provide window and screen\(monitor) abstractions, which leads to potential issues which should be handled by developer. 

The most simple way would be to provide a property to set scaling factor, however it still would be an issue in dual monitor setup, where each monitor has its own scaling factor - meaning that the developer should handle it on his side.

**Comment by SpinyOwl** [comment]
The latest version `4.2.0` contains new functionality which enables automatic UI scaling for window on monitor with scaling enabled.

Please take a look at it and leave your feedback, I really appreciate it!🙂

**Comment by SpinyOwl** [comment]
Hello @Thewbi!

The latest version `4.2.0` contains new functionality which enables automatic UI scaling for window on monitor with scaling enabled.

Please take a look at it and leave your feedback, I really appreciate it!🙂
