### ISSUE TITLE
Memory Leak in NvgRenderUtils#renderShadow

### ISSUE THREAD

**Issue by GeMoschen** [SpinyOwl/legui#99]
https://github.com/SpinyOwl/legui/blob/8fb4beb716db500c366fd72db2c48a68d3e18088/src/main/java/org/liquidengine/legui/system/renderer/nvg/util/NvgRenderUtils.java#L300

There is a huge memory leak when rendering themes with shadows. It will eat up your complete memory after a few minutes (I got 16GB of RAM full in about 10 minutes with the Example-Demo).

To fix this, you need to free the created colors in NvgRenderUtils#renderShadow.

Missing statements (after line 300):
```
colorA.free();
colorB.free();
```

**Comment by ShchAlexander** [comment]
Hello @GeMoschen!

Thank you very much for issue ticket! 
Going to create fix ASAP and create new artifact with fix.

Regards, 
Alex

**Comment by ShchAlexander** [comment]
Fixed. Published under `1.4.6-SNAPSHOT` version.

**Comment by GeMoschen** [comment]
Thanks a lot! :)
